package dragonforce.song.generator.pkg2;

import java.util.Random;

/**
 * @author Brandon Costa
 * Stores all the words used for generating the songs. 
 */
public class Words {
    //the word, syllables, end rhyme, plural/singular
    
    //a list of all viable prepositions
    private static final Word PREPOSITIONS[] = {
        new Word("with", 1),
        new Word("at", 1),
        new Word("from", 1),
        new Word("into", 2),
        new Word("during", 2),
        new Word("until", 2),
        new Word("against", 2),
        new Word("among", 2),
        new Word("throughout", 2),
        new Word("despite", 2),
        new Word("towards", 2),
        new Word("upon", 2),
        new Word("to", 1),
        new Word("in", 1),
        new Word("for", 1),
        new Word("on", 1),
        new Word("by", 1),
        new Word("over", 2),
        new Word("before", 2),
        new Word("between", 2),
        new Word("after", 2),
        new Word("since", 1),
        new Word("without", 2),
        new Word("under", 2),
        new Word("within", 2),
        new Word("beyond", 2),
        new Word("across", 2),
        new Word("behind", 2),
        new Word("around", 2),
        new Word("above", 2),
        new Word("near", 1)
    };
    
    //a list of all viable adjectives
    private static final Word ADJECTIVES[] = {
        new Word("cold", 1),
        new Word("winter", 2),
        new Word("eternal", 3),
        new Word("death's", 1),
        new Word("tough", 1),
        new Word("evil", 1),
        new Word("hard", 1),
        new Word("blackest", 2),
        new Word("scattered", 2),
        new Word("wasted", 2),
        new Word("free", 1),
        new Word("banished", 2),
        new Word("desperate", 3),
        new Word("endless", 2),
        new Word("far", 1),
        new Word("lost", 1),
        new Word("bloody", 2),
        new Word("red", 1),
        new Word("dawning", 2),
        new Word("valiant", 2),
        new Word("heroic", 3),
        new Word("strong", 1),
        new Word("powerful", 3),
        new Word("darkest", 2),
        new Word("fallen", 2),
        new Word("crystal", 2),
        new Word("darkened", 2),
        new Word("soaring", 2),
        new Word("flying", 2),
        new Word("shining", 2),
        new Word("distant", 2),
        new Word("long", 1),
        new Word("epic", 2),
        new Word("stark", 1),
        new Word("hot", 1),
        new Word("burning", 2),
        new Word("summer", 2),
        new Word("desolate", 2),
        new Word("flooded", 2),
        new Word("unknown", 2),
        new Word("worthless", 2),
        new Word("triumphant", 3),
        new Word("blazing", 2),
        new Word("fire's", 1),
        new Word("raging", 2),
        new Word("fatal", 2),
        new Word("immortal", 3),
        new Word("mortal", 2),
        new Word("wounded", 2),
        new Word("promised", 2),
        new Word("blinded", 2),
        new Word("blighted", 2),
        new Word("poisoned", 2),
        new Word("bleeding", 2),
        new Word("corrupted", 3),
        new Word("deadly", 1),
        new Word("emerald", 3),
        new Word("diamond", 2),
        new Word("ruby", 2),
        new Word("golden", 2),
        new Word("silvered", 2),
        new Word("crashing", 2),
        new Word("descending", 3),
        new Word("rising", 2),
        new Word("storming", 2),
        new Word("marching", 2),
        new Word("breaking", 2),
        new Word("bright", 1),
        new Word("everlasting", 4),
        new Word("brighter", 2),
        new Word("dark", 1),
        new Word("darker", 2),
        new Word("silent", 2),
        new Word("shattered", 2),
        new Word("still", 1),
        new Word("barren", 2),
        new Word("conquered", 2),
        new Word("true", 1),
        new Word("false", 1),
        new Word("falling", 2),
        new Word("crying", 2),
        new Word("healed", 1),
        new Word("broken", 2),
        new Word("weak", 1),
        new Word("sealed", 1),
        new Word("crawling", 2),
        new Word("liberated", 4),
        new Word("thundering", 3),
        new Word("last", 1),
        new Word("final", 2)
    };
    
    //a list of all viable singular nouns
    private static final Word SINGULAR_NOUNS[] = {
        new Word("morning", 2),
        new Word("time", 1),
        new Word("light", 1),
        new Word("flame", 1),
        new Word("death", 1),
        new Word("reign", 1),
        new Word("fight", 1),
        new Word("darkness", 2),
        new Word("sound", 1),
        new Word("evil", 2),
        new Word("laughter", 2),
        new Word("world", 1),
        new Word("steel", 1),
        new Word("fighting", 2),
        new Word("wasteland", 2),
        new Word("soul", 1),
        new Word("body", 2),
        new Word("shore", 1),
        new Word("plane", 1),
        new Word("domain", 2),
        new Word("fire", 1),
        new Word("pain", 1),
        new Word("day", 1),
        new Word("thunderstorm", 3),
        new Word("wilderness", 3),
        new Word("quest", 1),
        new Word("sundown", 2),
        new Word("moonlight", 2),
        new Word("heart", 1),
        new Word("misery", 3),
        new Word("dream", 1),
        new Word("life", 1),
        new Word("destiny", 3),
        new Word("lifetime", 2),
        new Word("love", 1),
        new Word("blood", 1),
        new Word("lightning", 2),
        new Word("sky", 1),
        new Word("hand", 1),
        new Word("heaven", 2),
        new Word("eye", 1),
        new Word("resentment", 3),
        new Word("mind", 1),
        new Word("plight", 1),
        new Word("land", 1),
        new Word("freedom", 2),
        new Word("star", 1),
        new Word("reality", 4),
        new Word("desperation", 4),
        new Word("curse", 1),
        new Word("seal", 1),
        new Word("man", 1),
        new Word("hero", 2),
        new Word("angel", 2),
        new Word("battle", 2),
        new Word("storm", 1),
        new Word("horizon", 3),
        new Word("call", 1),
        new Word("sorrow", 2),
        new Word("truth", 1),
        new Word("lie", 1),
        new Word("justice", 2),
        new Word("starlight", 2),
        new Word("memory", 3),
        new Word("year", 1),
        new Word("wind", 1),
        new Word("demon", 2),
        new Word("shadow", 2),
        new Word("mercy", 2),
        new Word("dawn", 1),
        new Word("silence", 2),
        new Word("sand", 1),
        new Word("power", 2),
        new Word("mountain", 2),
        new Word("valley", 2),
        new Word("tear", 1),
        new Word("unity", 3),
        new Word("reason", 2),
        new Word("gate", 1),
        new Word("fear", 1),
        new Word("edge", 1),
        new Word("door", 1),
        new Word("chant", 1),
        new Word("ground", 1),
        new Word("fall", 1),
        new Word("space", 1),
        new Word("voice", 1),
        new Word("dragon", 2),
        new Word("force", 1),
        new Word("gale", 1),
        new Word("tide", 1),
        new Word("warrior", 3),
        new Word("master", 2),
        new Word("knight", 1),
        new Word("night", 1),
        new Word("control", 2),
        new Word("temple", 2),
        new Word("thunder", 2),
        new Word("crime", 1),
        new Word("ascent", 2),
        new Word("hate", 1),
        new Word("desire", 2),
        new Word("suffering", 3),
        new Word("sacrifice", 3),
        new Word("journey", 2),
        new Word("boundary", 3),
        new Word("field", 1),
        new Word("twilight", 2),
        new Word("templar", 2),
        new Word("army", 2),
        new Word("fury", 2),
        new Word("ice", 1),
        new Word("sea", 1),
        new Word("legion", 2),
        new Word("punishment", 3),
        new Word("sun", 1),
        new Word("ash", 1),
        new Word("animosity", 5),
        new Word("innocence", 3),
        new Word("descent", 2),
        new Word("treason", 2),
        new Word("scream", 1),
        new Word("insanity", 4),
        new Word("glory", 2),
        new Word("victory", 3),
        new Word("chain", 1),
        new Word("one", 1),
        new Word("dark", 1),
        new Word("rain", 1),
        new Word("face", 1),
        new Word("mankind", 2),
        new Word("beginning", 3),
        new Word("labyrinth", 3),
        new Word("judgement", 2),
        new Word("eternity", 4),
        new Word("torture", 2),
        new Word("breath", 1),
        new Word("rage", 1),
        new Word("seam", 1),
        new Word("crown", 1),
        new Word("scene", 1),
        new Word("vain", 1),
        new Word("vein", 1),
        new Word("curtain", 2),
        new Word("humanity", 4),
        new Word("end", 1),
        new Word("revelation", 4),
        new Word("conviction", 3),
        new Word("sign", 1),
        new Word("blight", 1),
        new Word("poison", 2),
        new Word("emotion", 3),
        new Word("liberty", 3),
        new Word("war", 1),
        new Word("god", 1),
        new Word("moon", 1)
    };
    
    //a list of all viable plural nouns
    private static final Word PLURAL_NOUNS[] = {
        new Word("mornings", 2),
        new Word("times", 1),
        new Word("lights", 1),
        new Word("flames", 1),
        new Word("deaths", 1),
        new Word("reigns", 1),
        new Word("fights", 1),
        new Word("sounds", 1),
        new Word("evils", 2),
        new Word("worlds", 1),
        new Word("wastelands", 2),
        new Word("souls", 1),
        new Word("bodies", 2),
        new Word("shores", 1),
        new Word("planes", 1),
        new Word("domains", 2),
        new Word("fires", 1),
        new Word("pains", 1),
        new Word("days", 1),
        new Word("moons", 1),
        new Word("thunderstorms", 3),
        new Word("quests", 1),
        new Word("sundowns", 2),
        new Word("hearts", 1),
        new Word("dreams", 1),
        new Word("lives", 1),
        new Word("lifetimes", 2),
        new Word("skies", 1),
        new Word("hands", 1),
        new Word("heavens", 2),
        new Word("eyes", 1),
        new Word("minds", 1),
        new Word("plights", 1),
        new Word("lands", 1),
        new Word("stars", 1),
        new Word("realities", 4),
        new Word("curses", 2),
        new Word("seals", 1),
        new Word("men", 1),
        new Word("heroes", 2),
        new Word("angels", 2),
        new Word("battles", 2),
        new Word("storms", 1),
        new Word("horizons", 3),
        new Word("calls", 1),
        new Word("sorrows", 2),
        new Word("truths", 1),
        new Word("lies", 1),
        new Word("memories", 3),
        new Word("years", 1),
        new Word("winds", 1),
        new Word("demons", 2),
        new Word("shadows", 2),
        new Word("dawns", 1),
        new Word("sands", 1),
        new Word("powers", 2),
        new Word("mountains", 2),
        new Word("valleys", 2),
        new Word("tears", 1),
        new Word("reasons", 2),
        new Word("gates", 1),
        new Word("fears", 1),
        new Word("edges", 2),
        new Word("doors", 1),
        new Word("chants", 1),
        new Word("grounds", 1),
        new Word("voices", 2),
        new Word("dragons", 2),
        new Word("forces", 2),
        new Word("gales", 1),
        new Word("tides", 1),
        new Word("warriors", 3),
        new Word("masters", 2),
        new Word("knights", 1),
        new Word("nights", 1),
        new Word("temples", 2),
        new Word("thunders", 2),
        new Word("crimes", 1),
        new Word("desires", 3),
        new Word("sacrifices", 4),
        new Word("journeys", 2),
        new Word("boundaries", 3),
        new Word("fields", 1),
        new Word("templars", 2),
        new Word("armies", 2),
        new Word("furies", 2),
        new Word("seas", 1),
        new Word("legions", 2),
        new Word("punishments", 3),
        new Word("suns", 1),
        new Word("ashes", 2),
        new Word("screams", 1),
        new Word("victories", 3),
        new Word("chains", 1),
        new Word("rains", 1),
        new Word("faces", 2),
        new Word("beginnings", 3),
        new Word("labyrinths", 3),
        new Word("judgements", 2),
        new Word("eternities", 4),
        new Word("seams", 1),
        new Word("crowns", 1),
        new Word("scenes", 1),
        new Word("veins", 1),
        new Word("curtains", 2),
        new Word("ends", 1),
        new Word("revelations", 4),
        new Word("convictions", 3),
        new Word("signs", 1),
        new Word("poisons", 2),
        new Word("emotions", 3),
        new Word("liberties", 3),
        new Word("wars", 1),
        new Word("gods", 1)
    };
    
    //a list of all viable ing verbs
    private static final Word ING_VERBS[] = {
        new Word("riding", 2),
        new Word("fighting", 2),
        new Word("mourning", 2),
        new Word("running", 2),
        new Word("burning", 2),
        new Word("falling", 2),
        new Word("feeling", 2),
        new Word("wasting", 2),
        new Word("flying", 2),
        new Word("watching", 2),
        new Word("knowing", 2),
        new Word("carrying", 3),
        new Word("waiting", 2),
        new Word("cracking", 2),
        new Word("slaying", 2),
        new Word("losing", 2),
        new Word("dawning", 2),
        new Word("raising", 2),
        new Word("banishing", 3),
        new Word("believing", 3),
        new Word("bleeding", 2),
        new Word("blighting", 2),
        new Word("breaking", 2),
        new Word("freeing", 2),
        new Word("calling", 2),
        new Word("shining", 2),
        new Word("brandishing", 3),
        new Word("crying", 2),
        new Word("searching", 2),
        new Word("blazing", 2),
        new Word("touching", 2),
        new Word("standing", 2),
        new Word("living", 2),
        new Word("dying", 2),
        new Word("staring", 2),
        new Word("gazing", 2),
        new Word("rising", 2),
        new Word("crossing", 2),
        new Word("smiting", 2),
        new Word("facing", 2),
        new Word("winning", 2),
        new Word("opening", 3),
        new Word("closing", 2),
        new Word("chanting", 2),
        new Word("fearing", 2),
        new Word("crushing", 2),
        new Word("piercing", 2),
        new Word("slashing", 2),
        new Word("blinding", 2),
        new Word("seeing", 2),
        new Word("lighting", 2),
        new Word("storming", 2),
        new Word("holding", 2),
        new Word("forcing", 2),
        new Word("rolling", 2),
        new Word("bursting", 2),
        new Word("challenging", 3),
        new Word("raging", 2),
        new Word("beating", 2),
        new Word("arising", 3),
        new Word("firing", 3),
        new Word("controlling", 3),
        new Word("looking", 2),
        new Word("taking", 2),
        new Word("stealing", 2),
        new Word("suffering", 3),
        new Word("spilling", 2),
        new Word("growing", 2),
        new Word("sacrificing", 4),
        new Word("lying", 2),
        new Word("seeking", 2),
        new Word("ascending", 3),
        new Word("reaching", 2),
        new Word("smashing", 2),
        new Word("crashing", 2),
        new Word("torturing", 3),
        new Word("screaming", 2),
        new Word("clashing", 2),
        new Word("praying", 2),
        new Word("blasting", 2),
        new Word("washing", 2),
        new Word("dreaming", 2),
        new Word("rejecting", 3),
        new Word("killing", 2),
        new Word("finding", 2),
        new Word("changing", 2),
        new Word("shattering", 3),
        new Word("blackening", 3),
        new Word("darkening", 3),
        new Word("brightening", 3),
        new Word("glowing", 2),
        new Word("hiding", 2),
        new Word("drawing", 2),
        new Word("creeping", 2),
        new Word("sailing", 2),
        new Word("bludgeoning", 3),
        new Word("conquering", 3),
        new Word("liberating", 4),
        new Word("forsaking", 3),
        new Word("paying", 2),
        new Word("judging", 2),
        new Word("silencing", 3),
        new Word("healing", 2),
        new Word("thundering", 3),
        new Word("locking", 2),
        new Word("remembering", 4),
        new Word("loading", 2),
        new Word("becoming", 3),
        new Word("ending", 2),
        new Word("beginning", 3),
        new Word("defending", 3),
        new Word("leaving", 2),
        new Word("escaping", 3),
        new Word("starting", 2),
        new Word("fading", 2)
    };
    
    //a list of all viable singular verbs
    private static final Word SINGULAR_VERBS[] = {
        new Word("rides", 1),
        new Word("fights", 1),
        new Word("mourns", 1),
        new Word("runs", 1),
        new Word("burns", 1),
        new Word("falls", 1),
        new Word("feels", 1),
        new Word("wastes", 1),
        new Word("flies", 1),
        new Word("watches", 2),
        new Word("knows", 1),
        new Word("carries", 2),
        new Word("waits", 1),
        new Word("cracks", 1),
        new Word("slays", 1),
        new Word("loses", 2),
        new Word("dawns", 1),
        new Word("raises", 2),
        new Word("banishes", 3),
        new Word("believes", 2),
        new Word("bleeds", 1),
        new Word("blights", 1),
        new Word("breaks", 1),
        new Word("frees", 1),
        new Word("calls", 1),
        new Word("shines", 1),
        new Word("brandishes", 3),
        new Word("cries", 1),
        new Word("searches", 2),
        new Word("blazes", 2),
        new Word("touches", 2),
        new Word("stands", 1),
        new Word("lives", 1),
        new Word("dies", 1),
        new Word("stares", 1),
        new Word("gazes", 2),
        new Word("rises", 2),
        new Word("crosses", 2),
        new Word("smites", 1),
        new Word("faces", 2),
        new Word("wins", 1),
        new Word("opens", 2),
        new Word("closes", 2),
        new Word("chants", 1),
        new Word("fears", 1),
        new Word("crushes", 2),
        new Word("pierces", 2),
        new Word("slashes", 2),
        new Word("blinds", 1),
        new Word("sees", 1),
        new Word("lights", 1),
        new Word("storms", 1),
        new Word("holds", 1),
        new Word("forces", 2),
        new Word("rolls", 1),
        new Word("bursts", 1),
        new Word("challenges", 3),
        new Word("rages", 2),
        new Word("beats", 1),
        new Word("arises", 3),
        new Word("fires", 2),
        new Word("controls", 2),
        new Word("looks", 1),
        new Word("takes", 1),
        new Word("steals", 1),
        new Word("suffers", 2),
        new Word("spills", 1),
        new Word("grows", 1),
        new Word("sacrifices", 4),
        new Word("lies", 1),
        new Word("seeks", 1),
        new Word("ascends", 2),
        new Word("reaches", 2),
        new Word("smashes", 2),
        new Word("crashes", 2),
        new Word("tortures", 2),
        new Word("screams", 1),
        new Word("clashes", 2),
        new Word("prays", 1),
        new Word("blasts", 1),
        new Word("washes", 2),
        new Word("dreams", 1),
        new Word("rejects", 2),
        new Word("kills", 1),
        new Word("finds", 1),
        new Word("changes", 2),
        new Word("shatters", 2),
        new Word("blackens", 2),
        new Word("darkens", 2),
        new Word("brightens", 2),
        new Word("glows", 1),
        new Word("hides", 1),
        new Word("draws", 1),
        new Word("creeps", 1),
        new Word("sails", 1),
        new Word("bludgeons", 2),
        new Word("conquers", 2),
        new Word("liberates", 3),
        new Word("forsakes", 2),
        new Word("pays", 1),
        new Word("judges", 2),
        new Word("silences", 3),
        new Word("heals", 1),
        new Word("thunders", 2),
        new Word("locks", 1),
        new Word("remembers", 3),
        new Word("loads", 1),
        new Word("becomes", 2),
        new Word("ends", 1),
        new Word("begins", 2),
        new Word("defends", 2),
        new Word("leaves", 1),
        new Word("escapes", 2),
        new Word("starts", 1),
        new Word("fades", 1)
    };
    
    //a list of all viable plural verbs
    private static final Word PLURAL_VERBS[] = {
        new Word("ride", 1),
        new Word("fight", 1),
        new Word("mourn", 1),
        new Word("run", 1),
        new Word("burn", 1),
        new Word("fall", 1),
        new Word("feel", 1),
        new Word("waste", 1),
        new Word("fly", 1),
        new Word("watch", 1),
        new Word("know", 1),
        new Word("carry", 2),
        new Word("wait", 1),
        new Word("crack", 1),
        new Word("slay", 1),
        new Word("lose", 1),
        new Word("dawn", 1),
        new Word("raise", 1),
        new Word("banish", 2),
        new Word("believe", 2),
        new Word("bleed", 1),
        new Word("blight", 1),
        new Word("break", 1),
        new Word("free", 1),
        new Word("call", 1),
        new Word("shine", 1),
        new Word("brandish", 2),
        new Word("cry", 1),
        new Word("search", 1),
        new Word("blaze", 1),
        new Word("touch", 1),
        new Word("stand", 1),
        new Word("live", 1),
        new Word("die", 1),
        new Word("stare", 1),
        new Word("gaze", 1),
        new Word("rise", 1),
        new Word("cross", 1),
        new Word("smite", 1),
        new Word("face", 1),
        new Word("win", 1),
        new Word("open", 2),
        new Word("close", 1),
        new Word("chant", 1),
        new Word("fear", 1),
        new Word("crush", 1),
        new Word("pierce", 1),
        new Word("slash", 1),
        new Word("blind", 1),
        new Word("see", 1),
        new Word("light", 1),
        new Word("storm", 1),
        new Word("hold", 1),
        new Word("force", 1),
        new Word("roll", 1),
        new Word("burst", 1),
        new Word("challenge", 2),
        new Word("rage", 1),
        new Word("beat", 1),
        new Word("arise", 2),
        new Word("fire", 2),
        new Word("control", 2),
        new Word("look", 1),
        new Word("take", 1),
        new Word("steal", 1),
        new Word("suffer", 2),
        new Word("spill", 1),
        new Word("grow", 1),
        new Word("sacrifice", 3),
        new Word("lie", 1),
        new Word("seek", 1),
        new Word("ascend", 2),
        new Word("reach", 1),
        new Word("smash", 1),
        new Word("crash", 1),
        new Word("torture", 2),
        new Word("scream", 1),
        new Word("clash", 1),
        new Word("pray", 1),
        new Word("blast", 1),
        new Word("wash", 1),
        new Word("dream", 1),
        new Word("reject", 2),
        new Word("kill", 1),
        new Word("find", 1),
        new Word("change", 1),
        new Word("shatter", 2),
        new Word("blacken", 2),
        new Word("darken", 2),
        new Word("brighten", 2),
        new Word("glow", 1),
        new Word("hide", 1),
        new Word("draw", 1),
        new Word("creep", 1),
        new Word("sail", 1),
        new Word("bludgeon", 2),
        new Word("conquer", 2),
        new Word("liberate", 3),
        new Word("forsake", 2),
        new Word("pay", 1),
        new Word("judge", 1),
        new Word("silence", 2),
        new Word("heal", 1),
        new Word("thunder", 2),
        new Word("lock", 1),
        new Word("remember", 3),
        new Word("load", 1),
        new Word("become", 2),
        new Word("end", 1),
        new Word("begin", 2),
        new Word("defend", 2),
        new Word("leave", 1),
        new Word("escape", 2),
        new Word("start", 1),
        new Word("fade", 1)
    };
    
    //intializes a random
    static Random rand = new Random();
    
    /**
     * Returns either a random singular noun or a random plural noun. 
     * @param type either "singular" or "plural"
     * @return a random noun of the specified type
     */
    public static Word noun(String type){
        switch(type){
            case("singular"):
                return SINGULAR_NOUNS[rand.nextInt(SINGULAR_NOUNS.length)];
            case("plural"):
                return PLURAL_NOUNS[rand.nextInt(PLURAL_NOUNS.length)];
        }
        return SINGULAR_NOUNS[rand.nextInt(SINGULAR_NOUNS.length)];
    }
    
    /**
     * Returns a random singular, plural, or ing verb. 
     * @param type either "ing", "singular", "plural", or "justplural"
     * @return a random verb of the specified type
     */
    public static Word verb(String type){
        switch(type){
            case("ing"):
                return ING_VERBS[rand.nextInt(ING_VERBS.length)];
            case("singular"):
                if(rand.nextBoolean()){
                    return SINGULAR_VERBS[rand.nextInt(SINGULAR_VERBS.length)];
                }
                return ING_VERBS[rand.nextInt(ING_VERBS.length)];
            case("plural"):
                if(rand.nextBoolean()){
                    return PLURAL_VERBS[rand.nextInt(PLURAL_VERBS.length)];
                }
                return ING_VERBS[rand.nextInt(ING_VERBS.length)];
            case("justplural"):
                return PLURAL_VERBS[rand.nextInt(PLURAL_VERBS.length)];
        }
        return ING_VERBS[rand.nextInt(ING_VERBS.length)];
    }
    
    /**
     * Returns a random preposition. 
     * @return a random preposition
     */
    public static Word prep(){
        return PREPOSITIONS[rand.nextInt(PREPOSITIONS.length)];
    }
    
    /**
     * Returns a random adjective. 
     * @return a random adjective
     */
    public static Word adj(){
        return ADJECTIVES[rand.nextInt(ADJECTIVES.length)];
    }
    
}